USE master;
GO

IF DB_ID(N'HealthcareInventoryDB') IS NOT NULL
BEGIN
    ALTER DATABASE HealthcareInventoryDB SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE HealthcareInventoryDB;
END;
GO

CREATE DATABASE HealthcareInventoryDB;
GO

ALTER DATABASE HealthcareInventoryDB SET RECOVERY SIMPLE;
GO

ALTER DATABASE HealthcareInventoryDB SET READ_COMMITTED_SNAPSHOT ON WITH ROLLBACK IMMEDIATE;
GO

USE HealthcareInventoryDB;
GO


